[build]
  base = "client/"
  publish = "build/"
  command = "yarn build"

[build.environment]
  NODE_VERSION = "14.20.1"
  YARN_VERSION = "1.22.19"
  REACT_APP_STAGE = "dev"
  REACT_APP_SERVER_URL = "http://52.9.216.244:8000"

